name: Java CI with Maven - Test and package
on:
  pull_request:
    branches: [ main ]
jobs:
  runs-on: ubuntu-latest
  steps:
    - name: placer dans le dépôt couran
      uses: actions/checkout@v4

    - name: setup java
      uses: actions/setup-java@v4
      with:
          distribution: 'corretto'
          java-version: '21'

      run: mvn –B package

